-- Database Migration V2: Feature Gap Remediation
-- Run this in the Supabase SQL Editor to enable full sync capabilities.

-- 1. ADD MISSING COLUMNS TO user_profiles
ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS phone text,
ADD COLUMN IF NOT EXISTS mt5_login text,
ADD COLUMN IF NOT EXISTS mt5_password text, -- Stored as plain/encrypted string per User Backup Request
ADD COLUMN IF NOT EXISTS signal_channels text,
ADD COLUMN IF NOT EXISTS publish_profit boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS publish_knowledge boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS publish_initials_only boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS ui_hints_enabled boolean DEFAULT true;

-- 2. ENSURE LOGS TABLE EXISTS (For Full Timeline)
CREATE TABLE IF NOT EXISTS activity_logs (
    id bigint generated by default as identity primary key,
    user_id text not null, -- Links to user_profiles.hwid
    action text not null,
    details text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ENABLE RLS (Security Best Practice) - Optional Recap
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- 4. CREATE POLICES (If not exist)
-- Allow Users to Insert/Select their own logs
CREATE POLICY "Enable insert for users based on user_id" ON activity_logs FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Enable select for users based on user_id" ON activity_logs FOR SELECT TO anon, authenticated USING (user_id = auth.uid()::text OR user_id = current_setting('request.header.x-hwid', true));

-- 5. ADMIN VIEW FOR PASSWORDS (If needed)
-- (Supabase Dashboard already allows Table View)
